(ns hanafuda-cljs.deck)

(def cards
  [{:id 0
    :mon :jan
    :type :normal}
   {:id 1
    :mon :jan
    :type :normal}
   {:id 2
    :mon :jan
    :type :scroll}
   {:id 3
    :mon :jan
    :type :special}
   {:id 4
    :mon :feb
    :type :normal}
   {:id 5
    :mon :feb
    :type :normal}
   {:id 6
    :mon :feb
    :type :scroll}
   {:id 7
    :mon :feb
    :type :symbol}
   {:id 8
    :mon :mar
    :type :normal}
   {:id 9
    :mon :mar
    :type :normal}
   {:id 10
    :mon :mar
    :type :scroll}
   {:id 11
    :mon :mar
    :type :special}
   {:id 12
    :mon :apr
    :type :normal}
   {:id 13
    :mon :apr
    :type :normal}
   {:id 14
    :mon :apr
    :type :scroll}
   {:id 15
    :mon :apr
    :type :symbol}
   {:id 16
    :mon :may
    :type :normal}
   {:id 17
    :mon :may
    :type :normal}
   {:id 18
    :mon :may
    :type :scroll}
   {:id 19
    :mon :may
    :type :symbol}
   {:id 20
    :mon :jun
    :type :normal}
   {:id 21
    :mon :jun
    :type :normal}
   {:id 22
    :mon :jun
    :type :scroll}
   {:id 23
    :mon :jun
    :type :symbol}
   {:id 24
    :mon :jul
    :type :normal}
   {:id 25
    :mon :jul
    :type :normal}
   {:id 26
    :mon :jul
    :type :scroll}
   {:id 27
    :mon :jul
    :type :symbol}
   {:id 28
    :mon :aug
    :type :normal}
   {:id 29
    :mon :aug
    :type :normal}
   {:id 30
    :mon :aug
    :type :symbol}
   {:id 31
    :mon :aug
    :type :special}
   {:id 32
    :mon :sep
    :type :normal}
   {:id 33
    :mon :sep
    :type :normal}
   {:id 34
    :mon :sep
    :type :scroll}
   {:id 35
    :mon :sep
    :type :symbol}
   {:id 36
    :mon :oct
    :type :normal}
   {:id 37
    :mon :oct
    :type :normal}
   {:id 38
    :mon :oct
    :type :scroll}
   {:id 39
    :mon :oct
    :type :symbol}
   {:id 40
    :mon :nov
    :type :normal}
   {:id 41
    :mon :nov
    :type :scroll}
   {:id 42
    :mon :nov
    :type :symbol}
   {:id 43
    :mon :nov
    :type :special}
   {:id 44
    :mon :dec
    :type :normal}
   {:id 45
    :mon :dec
    :type :normal}
   {:id 46
    :mon :dec
    :type :symbol}
   {:id 47
    :mon :dec
    :type :special}])


(defn create-deck []
  (shuffle cards))
